# Generated by Django 4.2.17 on 2025-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campervan',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campervan',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
